import { randomUUID, timingSafeEqual } from 'node:crypto';
import { createServer, type IncomingMessage, type Server as HttpServer, type ServerResponse } from 'node:http';
import { mkdir, readFile, stat } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { McpServer, ResourceTemplate } from '@modelcontextprotocol/server';
import { NodeStreamableHTTPServerTransport, localhostHostValidation, localhostOriginValidation } from '@modelcontextprotocol/node';
import { z } from 'zod';
import {
  createId, entityBase, nowIso,
  type Actor, type AsyncJob, type Id, type MediaAsset, type ProjectOperation, type ProjectTransaction,
} from '@aimuse/core';
import type { ExportRequest } from '../common/contracts';
import type { GenerationJobResult, GenerationRequest } from '../common/generation';
import { FairAgentMutationScheduler, type AgentMutationResult } from './agent-mutation-scheduler';
import { AudioEngineController } from './audio-engine';
import { AuthorityManager } from './authority-manager';
import { ExportManager } from './export-manager';
import { GenerationManager } from './generation-manager';
import { MediaManager } from './media-manager';
import { sha256File, unpackProjectPack } from './persistence';
import { PluginManager } from './plugin-manager';
import { ProjectService } from './project-service';
import { buildTraceReplayAudit, sha256Json, type ReplayableTraceEntry } from './trace-replay-audit';

const PORT_START = 48300; const PORT_END = 48331; const MAX_BODY = 4 * 1024 * 1024; const SHOW_ACK_LIMIT = 64; const SHOW_ACK_RETENTION_MS = 5 * 60 * 1_000; const COLORS = ['#8b5cf6', '#06b6d4', '#f97316', '#10b981', '#ec4899', '#3b82f6'];
const SHOW_REQUEST_ID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
interface McpSession { actor: Actor; mcp: McpServer; transport: NodeStreamableHTTPServerTransport; resourceSubscriptions: Set<string> }
interface PortFile { version: 1; preferredPort: number }
interface PendingAction { actor: Actor; run: (actor: Actor) => Promise<unknown> }
export type ShowAcknowledgementRejection = 'duplicate-request' | 'instance-mismatch' | 'malformed-request' | 'profile-mismatch' | 'window-error';
export interface ShowAcknowledgement { requestId: string; status: 'accepted' | 'pending' | 'rejected'; pid: number; instanceId: string; profileId: string; receivedAt: string; acknowledgedAt?: string; attempts: number; reason?: ShowAcknowledgementRejection }
class McpHttpError extends Error { constructor(readonly status: number, readonly code: string, message: string) { super(message); } }

function safeEqual(left: string, right: string): boolean { const a = Buffer.from(left); const b = Buffer.from(right); return a.byteLength === b.byteLength && timingSafeEqual(a, b); }
interface NextStep { tool?: string; arguments?: Record<string, unknown>; guidance: string; humanRequired?: boolean }
function inferredNext(value: unknown): NextStep | undefined {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return undefined;
  const record = value as Record<string, unknown>;
  const jobId = typeof record.jobId === 'string' ? record.jobId : typeof record.id === 'string' && typeof record.status === 'string' ? record.id : undefined;
  if (jobId && record.status === 'waiting-for-user') return { tool: 'job_manage', arguments: { action: 'wait', jobId, timeoutMs: 0 }, guidance: 'A human must approve or deny this request in AIMuse. Agents cannot approve jobs; poll this owned job after the human decision.', humanRequired: true };
  if (jobId && !['completed', 'failed', 'cancelled'].includes(String(record.status ?? 'queued'))) return { tool: 'job_manage', arguments: { action: 'wait', jobId, timeoutMs: 1_000 }, guidance: 'Poll this owned job with a bounded wait, then inspect its terminal result.' };
  if (record.error === 'no_open_project') return { tool: 'project_manage', arguments: { action: 'list' }, guidance: 'List projects, then activate, open, or create one before retrying.' };
  if (record.error === 'path_required') return { tool: 'project_manage', arguments: { action: 'save', path: '<approved-folder>' }, guidance: 'Supply an approved destination path, or save a project that already has a working-folder path.' };
  if (record.error === 'invalid_arguments') return { tool: 'aimuse_help', arguments: { topic: 'tool-contracts' }, guidance: 'Read the tool contract, then retry with only the fields allowed for the selected action.' };
  return undefined;
}
function jsonText(value: unknown, explicitNext?: NextStep) {
  const next = explicitNext ?? inferredNext(value);
  const payload = next && value && typeof value === 'object' && !Array.isArray(value) ? { ...(value as Record<string, unknown>), next } : value;
  return { content: [{ type: 'text' as const, text: JSON.stringify(payload, null, 2) }], structuredContent: { data: payload, ...(next ? { next } : {}) } };
}
function terminal(status: AsyncJob['status']): boolean { return ['completed', 'failed', 'cancelled'].includes(status); }
function jobSummary(job: AsyncJob): Record<string, unknown> { const summary = { id: job.id, projectId: job.projectId, kind: job.kind, status: job.status, progress: job.progress, message: job.message, createdAt: job.createdAt, updatedAt: job.updatedAt, error: job.error, result: terminal(job.status) ? job.result : undefined, dependency: job.status === 'waiting-for-user' && job.approval ? { type: 'user-approval', approval: job.approval, guidance: 'A human must review this request in AIMuse. job_manage cannot approve it.' } : undefined }; return { ...summary, ...(inferredNext(summary) ? { next: inferredNext(summary) } : {}) }; }

const NextStepSchema = z.object({ tool: z.string().optional().describe('Tool to call next, when another MCP call can advance the workflow.'), arguments: z.record(z.string(), z.unknown()).optional().describe('Suggested arguments; placeholders must be replaced with real IDs or approved paths.'), guidance: z.string().describe('Plain-language next action and boundary.'), humanRequired: z.boolean().optional().describe('True when only a human in AIMuse can advance the dependency.') }).strict();
const ToolOutputSchema = z.object({ data: z.unknown().describe('The tool-specific result. Text content contains the same JSON for clients without structured-output support.'), next: NextStepSchema.optional().describe('Explicit follow-up for jobs, approvals, or incomplete calls.') }).strict();
const TOOL_OUTPUT = { outputSchema: ToolOutputSchema } as const;

interface ActionRule { description: string; required?: string[]; allowed?: string[] }
function actionSchema<const Actions extends readonly [string, ...string[]], Fields extends z.ZodRawShape>(actions: Actions, fields: Fields, rules: Record<Actions[number], ActionRule>) {
  const names = Object.keys(fields);
  const schema = z.object({ action: z.enum(actions).describe('Selects one action; tools/list oneOf branches define its valid fields.'), ...fields }).strict().superRefine((value, context) => {
    const candidate = value as unknown as Record<string, unknown>; const action = String(candidate.action) as Actions[number]; const rule = rules[action]; const allowed = new Set(rule.allowed ?? rule.required ?? []);
    for (const required of rule.required ?? []) if (candidate[required] === undefined) context.addIssue({ code: 'custom', path: [required], message: `${required} is required when action is ${action}.` });
    for (const name of names) if (candidate[name] !== undefined && !allowed.has(name)) context.addIssue({ code: 'custom', path: [name], message: `${name} is not valid when action is ${action}.` });
  });
  return schema.meta({ oneOf: actions.map((actionValue) => { const action = actionValue as Actions[number]; const rule = rules[action]; const allowed = new Set(rule.allowed ?? rule.required ?? []); const forbidden = names.filter((name) => !allowed.has(name)); return { title: `${action}: ${rule.description}`, properties: { action: { const: action } }, required: ['action', ...(rule.required ?? [])], ...(forbidden.length ? { not: { anyOf: forbidden.map((name) => ({ required: [name] })) } } : {}) }; }) });
}

const ProjectIdField = z.string().min(1).optional().describe('Open project ID. When allowed and omitted, AIMuse uses the active project.');
const SessionSchema = actionSchema(['join', 'inspect', 'update', 'leave'], {
  name: z.string().min(1).max(100).optional().describe('Agent display name; required to join.'), color: z.string().regex(/^#[0-9a-f]{6}$/i).optional().describe('Optional six-digit actor color.'), projectId: ProjectIdField,
  cursor: z.object({ tick: z.number().int().nonnegative(), trackId: z.string().optional(), tool: z.string().max(80).optional() }).strict().optional().describe('Current musical cursor and optional track/tool context.'),
  range: z.object({ startTick: z.number().int().nonnegative(), endTick: z.number().int().positive(), trackIds: z.array(z.string()).max(200).optional() }).strict().optional().describe('Current selected musical range; endTick must be after startTick.'),
  client: z.object({ product: z.string().max(100).optional(), model: z.string().max(160).optional(), effort: z.string().max(80).optional(), taskId: z.string().max(240).optional(), version: z.string().max(80).optional() }).strict().optional().describe('Non-secret client/model metadata shown in collaboration presence.'),
}, {
  join: { description: 'establish authenticated actor presence', required: ['name'], allowed: ['name', 'color', 'projectId', 'cursor', 'range', 'client'] }, inspect: { description: 'read presence and human locks' },
  update: { description: 'update this session cursor/range presence', allowed: ['projectId', 'cursor', 'range'] }, leave: { description: 'remove this session presence' },
});
const ProjectManageSchema = actionSchema(['list', 'new', 'activate', 'open', 'save', 'close', 'checkpoint', 'branch', 'compare', 'merge', 'discard-branch', 'pack', 'unpack'], {
  projectId: ProjectIdField, path: z.string().min(1).optional().describe('Local working-folder or pack source path; file authority applies.'), destination: z.string().min(1).optional().describe('Local output folder/file; file authority and no-overwrite rules apply.'), kind: z.enum(['song', 'sfx']).optional().describe('Project kind for new.'), name: z.string().max(200).optional().describe('Project, checkpoint, or branch name according to action.'), sampleRate: z.union([z.literal(44_100), z.literal(48_000), z.literal(96_000)]).optional().describe('New-project sample rate.'), bpm: z.number().min(20).max(400).optional().describe('New-project initial tempo.'), variantId: z.string().min(1).optional().describe('Named branch/variant ID.'), force: z.boolean().optional().describe('For close only: discard unsaved in-memory state without saving.'), overwrite: z.boolean().optional().describe('For pack only: explicit destination-overwrite intent; authority still applies.'),
}, {
  list: { description: 'list open projects' }, new: { description: 'create a project', allowed: ['kind', 'name', 'sampleRate', 'bpm'] }, activate: { description: 'activate a project', allowed: ['projectId'] }, open: { description: 'open an approved working folder', required: ['path'] }, save: { description: 'save active/specified project to its current or approved path', allowed: ['projectId', 'path'] }, close: { description: 'close a project, preserving dirty state unless force is explicit', allowed: ['projectId', 'force'] }, checkpoint: { description: 'create a durable project checkpoint', allowed: ['projectId', 'name'] }, branch: { description: 'create a named variant', allowed: ['projectId', 'name'] }, compare: { description: 'compare a named variant', required: ['variantId'] }, merge: { description: 'merge a named variant', required: ['variantId'] }, 'discard-branch': { description: 'discard a named variant', required: ['variantId'] }, pack: { description: 'start a portable-pack job', required: ['destination'], allowed: ['projectId', 'destination', 'overwrite'] }, unpack: { description: 'unpack to a new approved destination', required: ['path', 'destination'] },
});
const TransportSchema = actionSchema(['status', 'play', 'record', 'pause', 'stop', 'seek', 'loop'], { tick: z.number().int().nonnegative().optional().describe('Absolute musical tick for seek.'), loopEnabled: z.boolean().optional().describe('Whether looping is enabled.'), loopStartTick: z.number().int().nonnegative().optional().describe('Inclusive loop start tick.'), loopEndTick: z.number().int().positive().optional().describe('Exclusive loop end tick.'), recordingSource: z.enum(['microphone', 'midi-input']).optional().describe('Physical recording source; requires policy or human approval.') }, {
  status: { description: 'read transport state' }, play: { description: 'start playback' }, record: { description: 'request policy-gated recording', allowed: ['recordingSource'] }, pause: { description: 'pause playback' }, stop: { description: 'stop playback' }, seek: { description: 'seek to an absolute tick', required: ['tick'] }, loop: { description: 'configure looping', required: ['loopEnabled'], allowed: ['loopEnabled', 'loopStartTick', 'loopEndTick'] },
});
const MediaSchema = actionSchema(['list', 'import', 'analyze', 'audition', 'consolidate', 'separate'], { projectId: ProjectIdField, paths: z.array(z.string().min(1)).min(1).max(512).optional().describe('Local media paths; inline bytes are never accepted.'), assetId: z.string().min(1).optional().describe('Project media asset ID.'), trackId: z.string().min(1).optional().describe('Destination or single audition track ID.'), trackIds: z.array(z.string()).max(200).optional().describe('Optional audition/consolidation track subset.'), startTick: z.number().int().nonnegative().optional(), endTick: z.number().int().positive().optional(), placeAtTick: z.number().int().nonnegative().optional().describe('Consolidated clip placement tick.'), adapter: z.string().optional().describe('Explicit source-separation adapter; none is configured by default.') }, {
  list: { description: 'list project assets', allowed: ['projectId'] }, import: { description: 'import approved local paths', required: ['paths'], allowed: ['projectId', 'paths'] }, analyze: { description: 'analyze one asset', required: ['assetId'], allowed: ['projectId', 'assetId'] }, audition: { description: 'start an auditory observation render job', allowed: ['projectId', 'trackId', 'trackIds', 'startTick', 'endTick'] }, consolidate: { description: 'render and optionally place consolidated audio', allowed: ['projectId', 'trackId', 'trackIds', 'startTick', 'endTick', 'placeAtTick'] }, separate: { description: 'request an explicitly configured separation adapter', allowed: ['projectId', 'adapter'] },
});
const PluginSchema = actionSchema(['catalog', 'scan', 'instantiate', 'set-parameter', 'set-preset', 'bypass', 'remove'], { projectId: ProjectIdField, roots: z.array(z.string()).max(50).optional().describe('Optional local scan roots.'), trackId: z.string().min(1).optional(), pluginId: z.string().min(1).optional(), deviceId: z.string().min(1).optional(), parameterId: z.string().min(1).optional(), value: z.number().optional(), presetName: z.string().min(1).max(500).optional(), bypassed: z.boolean().optional() }, {
  catalog: { description: 'read the plug-in catalog' }, scan: { description: 'start a local scan job', allowed: ['roots'] }, instantiate: { description: 'instantiate an allowed plug-in', required: ['trackId', 'pluginId'], allowed: ['projectId', 'trackId', 'pluginId'] }, 'set-parameter': { description: 'set a stable parameter ID', required: ['deviceId', 'parameterId', 'value'], allowed: ['projectId', 'deviceId', 'parameterId', 'value'] }, 'set-preset': { description: 'select a preset by name', required: ['deviceId', 'presetName'], allowed: ['projectId', 'deviceId', 'presetName'] }, bypass: { description: 'set device bypass state', required: ['deviceId'], allowed: ['projectId', 'deviceId', 'bypassed'] }, remove: { description: 'remove a device', required: ['deviceId'], allowed: ['projectId', 'deviceId'] },
});
const GenerationActionSchema = actionSchema(['capabilities', 'start', 'inspect', 'accept', 'reject', 'variation'], { jobId: z.string().min(1).optional().describe('Owned generation job ID.'), candidateId: z.string().min(1).optional().describe('Immutable candidate ID within the owned job.'), trackId: z.string().min(1).optional().describe('Optional destination track for accept.'), startTick: z.number().int().nonnegative().optional().describe('Optional destination tick for accept.'), request: z.lazy(() => GenerationSchema).optional().describe('Provider-neutral generation request; authority, credentials, and cost policy still apply.'), overrides: z.object({ prompt: z.string().min(1).max(10_000).optional(), seed: z.number().int().optional(), resultCount: z.number().int().min(1).max(4).optional() }).strict().optional().describe('Explicit variation overrides.') }, {
  capabilities: { description: 'read configured provider capabilities' }, start: { description: 'start a generation job', required: ['request'] }, inspect: { description: 'inspect an owned generation job', required: ['jobId'] }, accept: { description: 'accept an immutable candidate into the project', required: ['jobId', 'candidateId'], allowed: ['jobId', 'candidateId', 'trackId', 'startTick'] }, reject: { description: 'reject an immutable candidate', required: ['jobId', 'candidateId'] }, variation: { description: 'start an explicit variation of an owned job', required: ['jobId'], allowed: ['jobId', 'overrides'] },
});
const JobSchema = actionSchema(['list', 'inspect', 'wait', 'cancel', 'approval-dependency'], { jobId: z.string().min(1).optional().describe('Owned job ID; foreign IDs are indistinguishable from missing IDs.'), timeoutMs: z.number().int().min(0).max(30_000).optional().describe('Bounded wait duration. Zero performs one immediate observation.') }, {
  list: { description: 'list only this authenticated actor’s jobs' }, inspect: { description: 'inspect one owned job', required: ['jobId'] }, wait: { description: 'wait briefly for one owned job', required: ['jobId'], allowed: ['jobId', 'timeoutMs'] }, cancel: { description: 'request cancellation of one owned job', required: ['jobId'] }, 'approval-dependency': { description: 'inspect a human-only approval dependency without granting it', required: ['jobId'] },
});
const HistorySchema = actionSchema(['undo', 'redo'], { projectId: ProjectIdField }, { undo: { description: 'undo only this authenticated actor’s latest eligible edit', allowed: ['projectId'] }, redo: { description: 'redo only this authenticated actor’s latest eligible edit', allowed: ['projectId'] } });
const TraceReplaySchema = z.object({
  projectId: z.string().min(1).describe('Open project whose durable trace owns the transaction.'),
  transactionId: z.string().min(1).describe('Transaction ID selected from project_apply or aimuse://projects/{id}/trace.'),
}).strict();
const ProjectApplySchema = z.object({ projectId: z.string().min(1).describe('Open project ID to mutate.'), variantId: z.string().min(1).optional().describe('Required only when commitMode is branch.'), clientOperationId: z.string().min(1).max(240).describe('Caller-generated idempotency key; reuse returns duplicate rather than reapplying.'), label: z.string().min(1).max(500).describe('Human-readable intent shown in activity/history.'), operations: z.array(z.record(z.string(), z.unknown())).min(1).max(512).describe('Granular canonical operations with current expected entity revisions where supported.'), commitMode: z.enum(['direct', 'checkpointed', 'branch']).default('direct').describe('direct applies now; checkpointed forces a safety checkpoint; branch requires variantId.') }).strict().superRefine((value, context) => { if (value.commitMode === 'branch' && !value.variantId) context.addIssue({ code: 'custom', path: ['variantId'], message: 'variantId is required when commitMode is branch.' }); if (value.commitMode !== 'branch' && value.variantId) context.addIssue({ code: 'custom', path: ['variantId'], message: 'variantId is valid only when commitMode is branch.' }); }).meta({ allOf: [{ if: { properties: { commitMode: { const: 'branch' } }, required: ['commitMode'] }, then: { required: ['variantId'] } }] });

const GenerationSchema = z.object({
  projectId: z.string().describe('Open project receiving immutable candidates.'), provider: z.enum(['elevenlabs', 'stability', 'lyria']).describe('Exact configured provider; AIMuse never substitutes another provider.'), model: z.string().min(1).describe('Exact provider model allowed by authority policy.'), kind: z.enum(['music', 'sfx', 'audio-to-audio', 'section-replace']).describe('Requested generation capability.'), prompt: z.string().min(1).max(10_000).describe('Exact submitted prompt; no silent rewrite or retry.'), negativePrompt: z.string().max(10_000).optional(), lyrics: z.string().max(200_000).optional(), instrumental: z.boolean().default(true), durationMs: z.number().int().positive().describe('Requested output duration in milliseconds.'), resultCount: z.number().int().min(1).max(4).default(1).describe('Number of immutable candidates, one to four.'), seed: z.number().int().optional(), referenceAssetIds: z.array(z.string()).max(20).default([]), targetRange: z.object({ startTick: z.number().int().nonnegative(), endTick: z.number().int().positive() }).strict().optional(), structure: z.array(z.object({ name: z.string(), startMs: z.number().int().nonnegative(), endMs: z.number().int().positive(), prompt: z.string().optional(), lyrics: z.string().optional() }).strict()).max(30).optional(), seamlessLoop: z.boolean().optional(), outputFormat: z.enum(['wav', 'mp3', 'pcm', 'opus']).default('mp3'), rightsDeclaration: z.enum(['original', 'licensed', 'owned-reference']).describe('Caller declaration required for provenance and reference rights.'), estimatedCostMinor: z.number().int().nonnegative().optional().describe('Expected charge in minor currency units; unknown cost is separately budgeted.'), currency: z.string().max(10).optional(), providerOptions: z.record(z.string(), z.unknown()).default({}).describe('Explicit provider-specific options; never inferred from another provider.'),
}).strict();

const SERVER_INSTRUCTIONS = 'Call aimuse_help(getting-started), then session_manage(join). Use project_manage/project_observe before edits, project_apply with a unique clientOperationId for content changes, trace_replay for a non-mutating visualization of a selected durable transaction, and job_manage for every returned jobId. Human approvals cannot be granted through MCP. Submit approval-capable requests one at a time: while one is being prepared or awaits a human, another fails with approval_pending and creates no job. File access is policy-gated; public job reads are owner-scoped. project_apply and history_manage mutation admission is fair and bounded; retry only when a retryable queue response says to, and re-observe before issuing another non-idempotent history action.';
const MCP_GUIDE = `# AIMuse MCP guide

## Safe starting workflow

1. Call \`aimuse_help\` with \`getting-started\` and then \`session_manage\` with \`join\`.
2. Use \`project_manage list\` and \`project_observe\` before changing state.
3. Submit musical edits through \`project_apply\` with a unique \`clientOperationId\`, current entity revisions, a clear label, and the smallest useful operation set.
4. When a result contains \`jobId\` or \`next\`, follow that guidance with \`job_manage\`. Waiting approvals are human-only and must be reviewed in AIMuse. Do not submit another approval-capable request until the prior request is terminal; AIMuse fails a concurrent request with \`approval_pending\` and creates no second job.
5. Re-observe state after commits. Use \`history_manage\` for only your authenticated actor's undo/redo. Use \`trace_replay\` to visualize a selected durable transaction without reapplying it.

## Identity, collaboration, and privacy

The server assigns the authenticated actor ID. Agent-supplied transaction actors, timestamps, revisions, assets, provenance, checkpoints, and variants are not trusted. Presence is collaborative, while job summaries/details/results are visible only to the owning authenticated session; a foreign job ID is indistinguishable from a missing ID. Active human entity/time locks take priority and return a retryable locked result without mutation. Direct and branch project transactions plus actor-scoped undo/redo enter one four-lane actor-round-robin scheduler with bounded per-actor and global queues; backpressure is explicit and retryable. A queued history cancellation starts no mutation, while a running atomic history commit is not preempted. Because history actions are not idempotent, re-observe before issuing another one.

## Files, jobs, and approvals

Open/import/save/export paths are checked against the process-lifetime authority policy and overwrite rules. An out-of-policy operation creates an owner-only approval job and performs no file I/O. MCP has no approval action: a human must allow or deny the request in AIMuse. Poll with bounded \`job_manage wait\`, then inspect terminal output. A successful save records a durable, destination-free \`file.saved\` audit event with project and authenticated actor identity; it is separate from undoable musical history and does not increment the project revision.

## Tools and resources

Each tool's JSON Schema has action-specific \`oneOf\` branches and field descriptions. Use \`aimuse_help\` topics for progressive detail. Resources are optional convenience surfaces: \`aimuse://projects\`, \`aimuse://sessions\`, \`aimuse://plugins\`, this guide, project manifest/snapshot/change/trace templates, owner-only job detail, and bounded analysis/audition media. \`trace_replay\` is the public action for a selected durable transaction: it emits bounded visualization progress and returns a deterministic receipt proving whether canonical state stayed unchanged. Exact-URI subscriptions receive only matching project updates.

## Boundaries

Inline media bytes, provider substitution, agent approval, forged provenance, and generic server-owned operations are rejected. Provider calls require explicit configuration, credentials, authority, and budget. Recording and plug-in hosting can also require human approval. Use tool results—not assumptions about client support for instructions, prompts, or resources—as the authoritative next-step surface.`;

const HelpTopicSchema = z.enum(['getting-started', 'tool-contracts', 'projects-and-edits', 'jobs-and-approvals', 'files-and-audit', 'collaboration', 'resources']).describe('Focused help topic; omit for getting-started.');
function helpTopic(topic = 'getting-started'): Record<string, unknown> {
  const topics: Record<string, Record<string, unknown>> = {
    'getting-started': { workflow: ['session_manage join', 'project_manage list', 'project_observe', 'project_apply or a domain tool', 'trace_replay for selected durable transaction visualization', 'job_manage for returned jobId', 're-observe'], rules: ['Use unique clientOperationId values.', 'Treat next as actionable guidance.', 'A human alone can resolve approvals.'] },
    'tool-contracts': { guidance: 'Read tools/list. Every action tool exposes oneOf branches that declare required and forbidden fields; important fields and the structured output envelope are described. Invalid action/field combinations are rejected before execution.' },
    'projects-and-edits': { guidance: 'Observe before applying. project_apply is idempotent and actor-authenticated; branch commits require variantId. Server-owned assets/provenance/checkpoints/variants require their domain tools. Re-observe revisions after every commit. trace_replay visualizes a selected durable transaction and returns before/after canonical hashes; it never reapplies the transaction.' },
    'jobs-and-approvals': { guidance: 'Every job belongs to one authenticated actor. Use job_manage list/inspect/wait/cancel. waiting-for-user means a human must decide in AIMuse; MCP cannot approve. Submit one approval-capable request at a time: a concurrent request fails with approval_pending, creates no job, and reveals no incumbent owner, job, or request details. Foreign and missing IDs both return job_not_found.' },
    'files-and-audit': { guidance: 'File paths are canonicalized and authority-gated. Rejected access queues only the owner approval job and performs no I/O. Successful saves emit destination-free file.saved audit records without creating an undo step or changing project revision.' },
    collaboration: { guidance: 'Presence is shared and authenticated. Jobs/results stay owner-only. Human entity/time locks preempt conflicting agent edits; unrelated edits remain allowed. project_apply and actor undo/redo share four fair lanes with bounded actor/global queues and explicit retry guidance. Queued history cancellation starts no mutation; once running, an atomic history commit is not preempted. Actor undo/redo affects only that actor history and is not idempotent, so re-observe before issuing another history action.' },
    resources: { guidance: 'Resources are optional. aimuse://guide is complete; project manifest/snapshot/change/trace and media templates are observational. Use trace_replay with a project ID and transaction ID from the durable trace for a non-mutating visualization and deterministic audit receipt. aimuse://sessions filters jobs to the reader, and aimuse://jobs/{id} is owner-only. Subscriptions are exact URI strings.' },
  };
  return { topic, ...topics[topic], fullGuideResource: 'aimuse://guide' };
}

export interface McpHostOptions { appVersion: string; profileId: string; portSettingsPath: string; cacheRoot: string; projects: ProjectService; audio: AudioEngineController; authority: AuthorityManager; media: MediaManager; plugins: PluginManager; generation: GenerationManager; exports: ExportManager }

export class McpHost {
  private token = ''; private port?: number; private httpServer?: HttpServer; private readonly instanceId = randomUUID(); private readonly sessions = new Map<string, McpSession>(); private readonly pending = new Map<Id, PendingAction>(); private readonly showAcks = new Map<string, ShowAcknowledgement>(); private readonly mutationScheduler = new FairAgentMutationScheduler(); private lastRevisions = new Map<Id, number>();
  constructor(private readonly options: McpHostOptions) {
    options.projects.on('event', (event) => { if (event.type !== 'workspace') return; for (const project of event.snapshot.projects) if (this.lastRevisions.get(project.id) !== project.revision) { this.lastRevisions.set(project.id, project.revision); void this.notifyProject(project.id, project.revision); } });
    options.projects.on('approval-resolved', (job: AsyncJob, decision: string) => { const pending = this.pending.get(job.id); if (pending && decision !== 'deny') void this.runPending(job, pending); else if (decision === 'deny') this.pending.delete(job.id); });
  }

  async start(token: string): Promise<{ port: number; url: string; tokenHint: string; instanceId: string; profileId: string }> { this.token = token; const preferred = await this.readPreferredPort(); const ports = [preferred, ...Array.from({ length: PORT_END - PORT_START + 1 }, (_, index) => PORT_START + index)].filter((value, index, values) => value >= PORT_START && value <= PORT_END && values.indexOf(value) === index); let failure: unknown; for (const port of ports) try { await this.listen(port); this.port = port; await mkdir(resolve(this.options.portSettingsPath, '..'), { recursive: true }); await import('./persistence').then(({ atomicWriteFile }) => atomicWriteFile(this.options.portSettingsPath, `${JSON.stringify({ version: 1, preferredPort: port } satisfies PortFile)}\n`)); return { port, url: `http://127.0.0.1:${port}/mcp`, tokenHint: `••••${token.slice(-6)}`, instanceId: this.instanceId, profileId: this.options.profileId }; } catch (error) { failure = error; } throw failure instanceof Error ? failure : new Error('No AIMuse MCP port is available.'); }
  credentials(): { url?: string; token: string; instanceId: string; profileId: string } { return { url: this.port ? `http://127.0.0.1:${this.port}/mcp` : undefined, token: this.token, instanceId: this.instanceId, profileId: this.options.profileId }; }
  beginShowAcknowledgement(requestId: string): boolean {
    if (!SHOW_REQUEST_ID.test(requestId)) return false;
    const normalized = requestId.toLowerCase();
    const existing = this.showAcks.get(normalized);
    if (existing) {
      existing.status = 'rejected'; existing.reason = 'duplicate-request'; existing.attempts += 1; existing.acknowledgedAt = new Date().toISOString();
      return false;
    }
    this.pruneShowAcknowledgements();
    if (this.showAcks.size >= SHOW_ACK_LIMIT) return false;
    this.showAcks.set(normalized, { requestId: normalized, status: 'pending', pid: process.pid, instanceId: this.instanceId, profileId: this.options.profileId, receivedAt: new Date().toISOString(), attempts: 1 });
    return true;
  }
  completeShowAcknowledgement(requestId: string, status: 'accepted' | 'rejected', reason?: ShowAcknowledgementRejection): boolean {
    if (!SHOW_REQUEST_ID.test(requestId) || (status === 'accepted' && reason !== undefined) || (status === 'rejected' && reason === undefined)) return false;
    const acknowledgement = this.showAcks.get(requestId.toLowerCase());
    if (!acknowledgement || acknowledgement.status !== 'pending' || acknowledgement.attempts !== 1) return false;
    acknowledgement.status = status; acknowledgement.acknowledgedAt = new Date().toISOString();
    if (reason) acknowledgement.reason = reason;
    return true;
  }
  showAcknowledgements(): ShowAcknowledgement[] { return [...this.showAcks.values()].map((acknowledgement) => ({ ...acknowledgement })); }
  async stop(): Promise<void> { this.mutationScheduler.cancelQueued(); for (const session of this.sessions.values()) { session.resourceSubscriptions.clear(); this.options.projects.removePresence(session.actor.id); await session.mcp.close().catch(() => undefined); } this.sessions.clear(); if (this.httpServer) await new Promise<void>((resolvePromise) => this.httpServer!.close(() => resolvePromise())); this.httpServer = undefined; this.pending.clear(); this.showAcks.clear(); }
  cancelQueuedMutations(projectId?: Id): number { return this.mutationScheduler.cancelQueued(projectId ? { projectId } : {}); }

  private pruneShowAcknowledgements(now = Date.now()): void {
    for (const [requestId, acknowledgement] of this.showAcks) {
      if (acknowledgement.status === 'pending' || !acknowledgement.acknowledgedAt) continue;
      const acknowledgedAt = Date.parse(acknowledgement.acknowledgedAt);
      if (Number.isFinite(acknowledgedAt) && acknowledgedAt <= now - SHOW_ACK_RETENTION_MS) this.showAcks.delete(requestId);
    }
  }

  private async listen(port: number): Promise<void> { const validateHost = localhostHostValidation(); const validateOrigin = localhostOriginValidation(); const server = createServer((request, response) => { if (!validateHost(request, response) || !validateOrigin(request, response)) return; response.setHeader('cache-control', 'no-store'); response.setHeader('x-content-type-options', 'nosniff'); void this.handleRequest(request, response).catch((error) => { const status = error instanceof McpHttpError ? error.status : 500; const code = error instanceof McpHttpError ? error.code : 'mcp_request_failed'; if (!response.headersSent) response.writeHead(status, { 'content-type': 'application/json' }); if (!response.writableEnded) response.end(JSON.stringify({ error: code, message: error instanceof Error ? error.message : 'MCP request failed.' })); }); }); await new Promise<void>((resolvePromise, reject) => { server.once('error', reject); server.listen(port, '127.0.0.1', resolvePromise); }); this.httpServer = server; }
  private async handleRequest(request: IncomingMessage, response: ServerResponse): Promise<void> { const url = new URL(request.url ?? '/', `http://127.0.0.1:${this.port ?? PORT_START}`); if (url.pathname === '/health' && request.method === 'GET') { response.writeHead(200, { 'content-type': 'application/json' }); response.end(JSON.stringify({ name: 'AIMuse Engine', version: this.options.appVersion, status: 'ok', pid: process.pid, instanceId: this.instanceId, profileId: this.options.profileId, showAcknowledgements: this.showAcknowledgements(), uiRequired: false, audio: this.options.audio.status() })); return; } if (url.pathname !== '/mcp') { response.writeHead(404, { 'content-type': 'application/json' }); response.end('{"error":"not_found"}'); return; } const authorization = request.headers.authorization ?? ''; if (!authorization.startsWith('Bearer ') || !safeEqual(authorization.slice(7), this.token)) { response.writeHead(401, { 'content-type': 'application/json', 'www-authenticate': 'Bearer realm="AIMuse MCP"' }); response.end('{"error":"invalid_token"}'); return; } if (request.method === 'OPTIONS') { response.writeHead(204, { allow: 'GET, POST, DELETE, OPTIONS' }); response.end(); return; } const header = request.headers['mcp-session-id']; const sessionId = Array.isArray(header) ? header[0] : header; let session = sessionId ? this.sessions.get(sessionId) : undefined; const body = request.method === 'POST' ? await this.readBody(request) : undefined; if (!session) { const method = body && typeof body === 'object' && 'method' in body ? (body as { method?: unknown }).method : undefined; if (request.method !== 'POST' || method !== 'initialize') { response.writeHead(sessionId ? 404 : 400, { 'content-type': 'application/json' }); response.end(JSON.stringify({ error: sessionId ? 'unknown_session' : 'initialization_required' })); return; } if (this.sessions.size >= 32) { response.writeHead(503, { 'content-type': 'application/json', 'retry-after': '5' }); response.end('{"error":"session_limit"}'); return; } session = await this.createSession(); } await session.transport.handleRequest(request, response, body); if (request.method === 'DELETE' && sessionId) { this.sessions.delete(sessionId); session.resourceSubscriptions.clear(); this.mutationScheduler.cancelQueued({ actorId: session.actor.id }); this.options.projects.removePresence(session.actor.id); await session.mcp.close().catch(() => undefined); return; } const assigned = session.transport.sessionId; if (assigned && !this.sessions.has(assigned)) this.sessions.set(assigned, session); }
  private async readBody(request: IncomingMessage): Promise<unknown> { const chunks: Buffer[] = []; let bytes = 0; for await (const chunk of request) { const value = Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk); bytes += value.byteLength; if (bytes > MAX_BODY) throw new McpHttpError(413, 'body_too_large', 'MCP body exceeds 4 MiB.'); chunks.push(value); } if (!chunks.length) return undefined; try { return JSON.parse(Buffer.concat(chunks).toString('utf8')); } catch { throw new McpHttpError(400, 'invalid_json', 'MCP request body is not valid JSON.'); } }
  private async createSession(): Promise<McpSession> { const index = this.sessions.size; const session: McpSession = { actor: { id: createId('agent'), kind: 'agent', name: `Agent ${index + 1}`, color: COLORS[index % COLORS.length] }, mcp: undefined as unknown as McpServer, transport: new NodeStreamableHTTPServerTransport({ sessionIdGenerator: () => randomUUID() }), resourceSubscriptions: new Set() }; session.mcp = this.buildServer(session); await session.mcp.connect(session.transport); return session; }

  private buildServer(session: McpSession): McpServer {
    const server = new McpServer({ name: 'aimuse', version: this.options.appVersion }, { capabilities: { resources: { subscribe: true, listChanged: true }, tools: { listChanged: true } }, instructions: SERVER_INSTRUCTIONS }); const projects = this.options.projects;
    server.server.setRequestHandler('resources/subscribe', async (request) => { session.resourceSubscriptions.add(request.params.uri); return {}; });
    server.server.setRequestHandler('resources/unsubscribe', async (request) => { session.resourceSubscriptions.delete(request.params.uri); return {}; });
    server.registerResource('Open AIMuse projects', 'aimuse://projects', { title: 'Open AIMuse projects', mimeType: 'application/json' }, async (uri) => ({ contents: [{ uri: uri.href, mimeType: 'application/json', text: JSON.stringify(projects.snapshot(session.actor.id).projects) }] }));
    server.registerResource('AIMuse sessions', 'aimuse://sessions', { title: 'Collaboration presence and reader-owned jobs', description: 'Shared authenticated presence plus job summaries owned by this exact MCP session only.', mimeType: 'application/json' }, async (uri) => ({ contents: [{ uri: uri.href, mimeType: 'application/json', text: JSON.stringify({ presence: projects.getMcpInfo().sessions, jobs: projects.listJobs(session.actor.id).map(jobSummary) }) }] }));
    server.registerResource('AIMuse plug-in catalog', 'aimuse://plugins', { title: 'VST3 and CLAP catalog', mimeType: 'application/json' }, async (uri) => ({ contents: [{ uri: uri.href, mimeType: 'application/json', text: JSON.stringify(this.options.plugins.list()) }] }));
    server.registerResource('AIMuse MCP guide', 'aimuse://guide', { title: 'Complete AIMuse MCP guide', description: 'Optional full workflow, privacy, authority, job and discovery guidance.', mimeType: 'text/markdown' }, async (uri) => ({ contents: [{ uri: uri.href, mimeType: 'text/markdown', text: MCP_GUIDE }] }));
    const manifest = new ResourceTemplate('aimuse://projects/{id}/manifest', { list: undefined }); server.registerResource('AIMuse project manifest', manifest, { title: 'Project manifest', mimeType: 'application/json' }, async (uri, variables) => { const project = projects.getProject(String(variables.id)); if (!project) throw new Error('Project is not open.'); return { contents: [{ uri: uri.href, mimeType: 'application/json', text: JSON.stringify({ format: project.format, schemaVersion: project.schemaVersion, id: project.id, revision: project.revision, name: project.name, kind: project.kind, dirty: project.dirty, sampleRate: project.settings.sampleRate, tracks: Object.keys(project.tracks).length, clips: Object.keys(project.clips).length, assets: Object.keys(project.assets).length }) }] }; });
    const snapshot = new ResourceTemplate('aimuse://projects/{id}/snapshot', { list: undefined }); server.registerResource('AIMuse project snapshot', snapshot, { title: 'Canonical project snapshot', mimeType: 'application/json' }, async (uri, variables) => { const project = projects.getProject(String(variables.id)); if (!project) throw new Error('Project is not open.'); return { contents: [{ uri: uri.href, mimeType: 'application/json', text: JSON.stringify(project) }] }; });
    const changes = new ResourceTemplate('aimuse://projects/{id}/changes/{revision}', { list: undefined }); server.registerResource('AIMuse revision changes', changes, { title: 'Revision changes', mimeType: 'application/json' }, async (uri, variables) => ({ contents: [{ uri: uri.href, mimeType: 'application/json', text: JSON.stringify(projects.getChanges(String(variables.id), Number(variables.revision))) }] }));
    const trace = new ResourceTemplate('aimuse://projects/{id}/trace', { list: undefined }); server.registerResource('AIMuse transaction trace', trace, { title: 'Durable transaction trace', mimeType: 'application/x-ndjson' }, async (uri, variables) => ({ contents: [{ uri: uri.href, mimeType: 'application/x-ndjson', text: (await projects.listTrace(String(variables.id))).map((entry) => JSON.stringify(entry)).join('\n') }] }));
    const jobs = new ResourceTemplate('aimuse://jobs/{id}', { list: undefined }); server.registerResource('AIMuse job', jobs, { title: 'Reader-owned job status', description: 'Owner-only job detail; foreign IDs are indistinguishable from missing IDs.', mimeType: 'application/json' }, async (uri, variables) => { const job = projects.getJob(String(variables.id)); if (!job || job.ownerActorId !== session.actor.id) throw new Error('Job does not exist.'); return { contents: [{ uri: uri.href, mimeType: 'application/json', text: JSON.stringify(jobSummary(job)) }] }; });
    const media = new ResourceTemplate('aimuse://projects/{projectId}/media/{assetId}', { list: undefined }); server.registerResource('AIMuse analysis or audition media', media, { title: 'Analysis/audition media', mimeType: 'application/octet-stream' }, async (uri, variables) => { const projectId = String(variables.projectId); const assetId = String(variables.assetId); const project = projects.getProject(projectId); const asset = project?.assets[assetId]; const path = projects.getAssetSource(projectId, assetId); if (!asset || !path || !['analysis', 'audition'].includes(asset.kind)) throw new Error('Observation asset is unavailable.'); const bytes = await readFile(path); if (bytes.byteLength > 64 * 1024 * 1024) throw new Error('Observation asset exceeds the MCP resource limit.'); return { contents: [{ uri: uri.href, mimeType: asset.mimeType, blob: bytes.toString('base64') }] }; });

    server.registerTool('aimuse_help', { title: 'Learn AIMuse MCP workflows', description: 'Returns focused, model-readable workflow, privacy, authority, job, save-audit, and resource guidance. Call this first; use aimuse://guide only when the client supports resources.', inputSchema: z.object({ topic: HelpTopicSchema.optional() }).strict(), ...TOOL_OUTPUT, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ topic }) => jsonText(helpTopic(topic)));
    server.registerTool('session_manage', { title: 'Manage AIMuse session', description: 'Join before work; inspect shared presence/human locks; update this actor’s cursor/range; or leave. Returns the server-assigned actor, presence and locks.', inputSchema: SessionSchema, ...TOOL_OUTPUT, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ action, name, color, projectId, cursor, range, client }) => { if (action === 'leave') projects.removePresence(session.actor.id); else { if (name) session.actor.name = name; if (color) session.actor.color = color; if (client) session.actor.client = client; if (action !== 'inspect') projects.updatePresence({ actor: structuredClone(session.actor), projectId, cursor, range, queueDepth: projects.listJobs(session.actor.id).filter((job) => !terminal(job.status)).length, status: 'idle', joinedAt: nowIso() }); } return jsonText({ actor: session.actor, presence: projects.getMcpInfo().sessions, locks: projects.snapshot(session.actor.id).locks }); });

    server.registerTool('project_manage', { title: 'Manage AIMuse projects', description: 'Project lifecycle/branches. Returns project/workspace data, safe save audit, or a jobId; open/save/pack/unpack are authority-gated and jobs use job_manage.', inputSchema: ProjectManageSchema, ...TOOL_OUTPUT, annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: true } }, async (request) => {
      const projectId = request.projectId ?? projects.getActiveProjectId(); if (request.action === 'list') return jsonText(projects.snapshot(session.actor.id).projects); if (request.action === 'new') return jsonText(await projects.create({ kind: request.kind ?? 'song', name: request.name, sampleRate: request.sampleRate, bpm: request.bpm }, session.actor)); if (request.action === 'activate' && projectId) return jsonText(await projects.activate(projectId, session.actor.id)); if (request.action === 'close' && projectId) return jsonText(await projects.close(projectId, request.force ?? false)); if (request.action === 'checkpoint' && projectId) return jsonText(await projects.createCheckpoint(projectId, request.name ?? 'Agent checkpoint', session.actor)); if (request.action === 'branch' && projectId) return jsonText(await projects.createBranch(projectId, request.name ?? 'Agent variant', session.actor)); if (request.action === 'compare' && request.variantId) return jsonText(await projects.compareBranch(request.variantId)); if (request.action === 'merge' && request.variantId) return jsonText(await projects.mergeBranch(request.variantId, session.actor)); if (request.action === 'discard-branch' && request.variantId) return jsonText(await projects.discardBranch(request.variantId, session.actor)); if (request.action === 'pack' && projectId && request.destination) return this.startApprovalCapableJob(session, (reservationId) => this.options.exports.start({ projectId, kind: 'pack', destination: request.destination!, overwrite: request.overwrite ?? false }, session.actor, reservationId));
      if (request.action === 'open' && request.path) return this.fileAction(session, request.path, 'read', 'media', 'Open project folder', { action: 'open', path: resolve(request.path) }, async () => projects.open([request.path])); if (request.action === 'save' && projectId) { const target = request.path ?? projects.getProject(projectId)?.projectPath; if (!target) return jsonText({ error: 'path_required' }); return this.fileAction(session, target, 'write', 'save', 'Save project folder', { action: 'save', projectId, path: resolve(target) }, async (actor) => projects.save(projectId, target, actor)); } if (request.action === 'unpack' && request.path && request.destination) return this.multiFileAction(session, [{ path: request.path, mode: 'read' }, { path: request.destination, mode: 'write' }], 'pack', 'Unpack portable project', { action: 'unpack', path: resolve(request.path), destination: resolve(request.destination) }, async () => { const folder = await unpackProjectPack(request.path!, request.destination!); return projects.open([folder]); }); return jsonText({ error: 'invalid_arguments' });
    });

    server.registerTool('project_observe', { title: 'Observe AIMuse project', description: 'Read a canonical snapshot or revision diff before/after edits, with optional editor state, safe file-save audit, and bounded observation-resource references.', inputSchema: z.object({ projectId: ProjectIdField, variantId: z.string().min(1).optional().describe('Observe a named branch instead of the main project.'), sinceRevision: z.number().int().nonnegative().optional().describe('Return main-project transactions strictly after this revision instead of the full snapshot.'), includeEditor: z.boolean().default(false).describe('Include attached editor selection, transport and human locks.'), includeFileAudit: z.boolean().default(false).describe('Include durable destination-free file.saved records; these are not undoable content history.'), assetIds: z.array(z.string()).max(20).default([]).describe('Return resource references for these analysis/audition asset IDs.') }).strict(), ...TOOL_OUTPUT, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ projectId, variantId, sinceRevision, includeEditor, includeFileAudit, assetIds }) => { const id = projectId ?? projects.getActiveProjectId(); if (!id) return jsonText({ error: 'no_open_project' }); const project = variantId ? await projects.getBranch(variantId) : projects.getProject(id); if (!project) return jsonText({ error: 'project_not_open' }); const workspace = projects.snapshot(session.actor.id); return jsonText({ project: sinceRevision === undefined ? project : undefined, changes: sinceRevision === undefined || variantId ? undefined : projects.getChanges(id, sinceRevision), revision: project.revision, fileAudit: includeFileAudit ? projects.listFileAudit(id) : undefined, editor: includeEditor ? { selection: workspace.selection, transport: workspace.transport, locks: workspace.locks } : undefined, observations: assetIds.map((assetId) => { const asset = project.assets[assetId]; return asset ? { assetId, kind: asset.kind, mimeType: asset.mimeType, resource: `aimuse://projects/${id}/media/${assetId}` } : { assetId, error: 'not_found' }; }) }); });

    server.registerTool('project_apply', { title: 'Apply AIMuse transaction', description: 'Fairly schedules up to 512 idempotent content operations. Returns status plus revision/transaction/checkpoint, bounded conflict, or explicit retryable backpressure; AIMuse supplies trusted actor/time/provenance.', inputSchema: ProjectApplySchema, ...TOOL_OUTPUT, annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false } }, async ({ projectId, variantId, clientOperationId, label, operations, commitMode }) => {
      const forbidden = operations.find((operation) => ['asset.add', 'provenance.register', 'provenance.update', 'checkpoint.register', 'variant.register', 'variant.update'].includes(String(operation.kind)));
      if (forbidden) return jsonText({ status: 'conflict', message: `${String(forbidden.kind)} is server-owned. Use the corresponding media, generation, checkpoint, or branch tool.` });
      const transaction: ProjectTransaction = { id: createId('tx'), clientOperationId, projectId, actor: structuredClone(session.actor), label, createdAt: nowIso(), operations: operations as ProjectOperation[], checkpointPolicy: commitMode === 'checkpointed' ? 'required' : 'auto' };
      const scheduled = await this.submitMutation(session, projectId, operations.length,
        () => commitMode === 'branch' ? projects.applyBranch(variantId!, transaction, session.actor) : projects.apply(transaction, session.actor));
      if (!scheduled.accepted) {
        const scheduler = { code: scheduled.code, actorQueueDepth: scheduled.queueDepth, globalQueueDepth: scheduled.globalQueueDepth };
        if (scheduled.code === 'cancelled') return jsonText({ status: 'cancelled', message: scheduled.message, scheduler }, { tool: 'project_observe', arguments: { projectId }, guidance: 'Re-observe the project before deciding whether to submit the cancelled intent again.' });
        return jsonText({ status: 'busy', message: scheduled.message, conflict: { retryable: true, retryAfterMs: scheduled.retryAfterMs }, scheduler }, { guidance: `Wait at least ${scheduled.retryAfterMs} ms, then retry the same idempotent project_apply request.` });
      }
      return jsonText(scheduled.result);
    });

    server.registerTool('transport_manage', { title: 'Manage AIMuse transport', description: 'Read/control the shared transport and return its state. Seek/loop fields are action-specific; recording is policy-gated and may return a human-only job.', inputSchema: TransportSchema, ...TOOL_OUTPUT, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false } }, async ({ action, recordingSource, ...options }) => { if (action === 'status') return jsonText(this.options.audio.snapshot()); if (action === 'record') { const kind = recordingSource ?? 'microphone'; const decision = this.options.authority.recording(kind); if (!decision.allowed) return this.queueApproval(session, 'approval', decision.approvalKind ?? 'recording', 'Start recording', { action, kind }, async () => this.options.audio.transport('record', options)); } return jsonText(await this.options.audio.transport(action, options)); });
    server.registerTool('history_manage', { title: 'Manage actor history', description: 'Fairly schedules undo/redo for only this authenticated actor and returns commit/conflict, cancellation, or retryable backpressure; later work from other actors is preserved. History actions are not idempotent.', inputSchema: HistorySchema, ...TOOL_OUTPUT, annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: false } }, async ({ action, projectId }) => {
      const actor = structuredClone(session.actor);
      const id = projectId ?? projects.getActiveProjectId();
      if (!id) return jsonText(action === 'undo' ? await projects.undo(undefined, actor) : await projects.redo(undefined, actor));
      const scheduled = await this.submitMutation(session, id, 1, () => action === 'undo' ? projects.undo(id, actor) : projects.redo(id, actor));
      if (!scheduled.accepted) {
        const scheduler = { code: scheduled.code, actorQueueDepth: scheduled.queueDepth, globalQueueDepth: scheduled.globalQueueDepth };
        const next = { tool: 'project_observe', arguments: { projectId: id }, guidance: scheduled.code === 'cancelled'
          ? `No ${action} mutation started. Re-observe the project before deciding whether to issue a new history action.`
          : `Wait at least ${scheduled.retryAfterMs} ms, then re-observe the project before deciding whether to issue a new ${action}; history actions are not idempotent.` };
        if (scheduled.code === 'cancelled') return jsonText({ status: 'cancelled', message: scheduled.message, scheduler }, next);
        return jsonText({ status: 'busy', message: scheduled.message, conflict: { retryable: true, retryAfterMs: scheduled.retryAfterMs }, scheduler }, next);
      }
      return jsonText(scheduled.result);
    });
    server.registerTool('trace_replay', { title: 'Replay durable transaction trace', description: 'Visualizes one selected durable transaction without applying operations. Returns a deterministic, credential-free receipt with source and canonical before/after hashes.', inputSchema: TraceReplaySchema, ...TOOL_OUTPUT, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ projectId, transactionId }) => {
      const before = projects.getProject(projectId);
      if (!before) return jsonText({ error: 'no_open_project', projectId });
      const entry = await projects.findTrace(projectId, transactionId);
      if (!entry?.transaction) return jsonText({ error: 'trace_transaction_not_found', projectId, transactionId }, { tool: 'aimuse_help', arguments: { topic: 'resources' }, guidance: `Read aimuse://projects/${projectId}/trace and retry with a transaction ID present in that durable trace.` });
      const replay = await projects.replayTrace(projectId, transactionId);
      if (!replay.replaying) return jsonText({ error: 'trace_replay_unavailable', projectId, transactionId, reason: replay.reason });
      const replayedEntry = await projects.findTrace(projectId, transactionId);
      if (!replayedEntry?.transaction || sha256Json(replayedEntry) !== sha256Json(entry)) return jsonText({ error: 'trace_changed_during_replay', projectId, transactionId });
      const after = projects.getProject(projectId);
      if (!after) return jsonText({ error: 'project_closed_during_trace_replay', projectId, transactionId });
      return jsonText(buildTraceReplayAudit(entry as ReplayableTraceEntry, before, after));
    });

    server.registerTool('media_manage', { title: 'Manage AIMuse media', description: 'List/import/analyze/render project media. Imports accept only authority-approved local paths; inline bytes are never accepted. Audition/consolidate return a jobId.', inputSchema: MediaSchema, ...TOOL_OUTPUT, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true } }, async ({ action, projectId, paths, assetId, trackId, trackIds, startTick, endTick, placeAtTick, adapter }) => { const id = projectId ?? projects.getActiveProjectId(); const project = id ? projects.getProject(id) : undefined; if (!id || !project) return jsonText({ error: 'no_open_project' }); if (action === 'list') return jsonText(Object.values(project.assets)); if (action === 'analyze' && assetId) return jsonText(await this.options.media.analyze(id, assetId, session.actor)); if (action === 'separate') return jsonText({ error: 'adapter_unavailable', adapter, message: 'No source-separation adapter is configured; AIMuse did not substitute a provider.' }, { tool: 'aimuse_help', arguments: { topic: 'tool-contracts' }, guidance: 'Configure and name an explicit adapter in a separately authorized workflow; AIMuse will not substitute a provider.' }); if ((action === 'audition' || action === 'consolidate')) return jsonText(this.startAudition(id, session.actor, startTick, endTick, trackIds ?? (trackId ? [trackId] : undefined), action === 'consolidate', trackId, placeAtTick)); if (action === 'import' && paths?.length) return this.multiFileAction(session, paths.map((path) => ({ path, mode: 'read' as const })), 'media', 'Import media', { action, paths: paths.map((path) => resolve(path)), projectId: id }, async (actor) => this.options.media.importPaths(id, paths, actor, true)); return jsonText({ error: 'invalid_arguments' }); });

    server.registerTool('plugin_manage', { title: 'Manage VST3 and CLAP plug-ins', description: 'Catalog/scan or mutate plug-in devices with action-specific IDs. Scan returns a jobId; instantiate is allowlist-gated and may require human approval.', inputSchema: PluginSchema, ...TOOL_OUTPUT, annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: true } }, async ({ action, projectId, roots, trackId, pluginId, deviceId, parameterId, value, presetName, bypassed }) => { if (action === 'catalog') return jsonText(this.options.plugins.list()); if (action === 'scan') return jsonText(this.options.plugins.scan(roots, session.actor)); const id = projectId ?? projects.getActiveProjectId(); const project = id ? projects.getProject(id) : undefined; if (!id || !project) return jsonText({ error: 'no_open_project' }); if (action === 'instantiate' && trackId && pluginId) { const decision = this.options.authority.plugin(pluginId); if (!decision.allowed) return this.queueApproval(session, 'plugin-host', decision.approvalKind ?? 'plugin', 'Instantiate plug-in', { action, projectId: id, trackId, pluginId }, async (actor) => this.options.plugins.instantiate(id, trackId, pluginId, actor, true)); return jsonText(await this.options.plugins.instantiate(id, trackId, pluginId, session.actor)); } if (!deviceId || !project.devices[deviceId]) return jsonText({ error: 'device_not_found' }); let operation: ProjectOperation; if (action === 'set-parameter' && parameterId && value !== undefined) operation = { kind: 'device.parameter.set', deviceId, parameterId, value, expectedRevision: project.devices[deviceId].revision }; else if (action === 'set-preset' && presetName) operation = { kind: 'device.update', deviceId, changes: { presetName }, expectedRevision: project.devices[deviceId].revision }; else if (action === 'bypass') operation = { kind: 'device.update', deviceId, changes: { bypassed: bypassed ?? true }, expectedRevision: project.devices[deviceId].revision }; else if (action === 'remove') operation = { kind: 'device.delete', deviceId, expectedRevision: project.devices[deviceId].revision }; else return jsonText({ error: 'invalid_arguments' }); return jsonText(await projects.apply({ id: createId('tx'), clientOperationId: createId('plugin-operation'), projectId: id, actor: session.actor, label: `${action}: ${project.devices[deviceId].name}`, createdAt: nowIso(), operations: [operation], checkpointPolicy: 'none' }, session.actor)); });

    server.registerTool('generation_manage', { title: 'Manage generated music and SFX', description: 'Provider-neutral generation lifecycle. Job/candidate actions are owner-scoped; provider configuration, credentials, budget and authority remain explicit.', inputSchema: GenerationActionSchema, ...TOOL_OUTPUT, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true } }, async ({ action, jobId, candidateId, trackId, startTick, request, overrides }) => { if (action === 'capabilities') return jsonText(await this.options.generation.capabilities()); if (action === 'start' && request) return this.startApprovalCapableJob(session, (reservationId) => this.options.generation.start(request as GenerationRequest, session.actor, reservationId)); const owned = jobId ? projects.getJob<GenerationJobResult>(jobId) : undefined; if (!owned || owned.ownerActorId !== session.actor.id) return jsonText({ error: 'generation_job_not_found' }); if (action === 'inspect') return jsonText(jobSummary(owned)); if (action === 'accept' && candidateId) return jsonText(await this.options.generation.accept(owned.id, candidateId, trackId, startTick, session.actor)); if (action === 'reject' && candidateId) return jsonText(this.options.generation.reject(owned.id, candidateId)); if (action === 'variation') { const original = owned.result?.request; if (!original) return jsonText({ error: 'generation_job_not_found' }); return this.startApprovalCapableJob(session, (reservationId) => this.options.generation.start({ ...original, ...overrides, seed: overrides?.seed ?? (original.seed === undefined ? undefined : original.seed + 1) }, session.actor, reservationId)); } return jsonText({ error: 'invalid_arguments' }); });

    server.registerTool('export_manage', { title: 'Export AIMuse project', description: 'Starts an owner-scoped export job. Destination authority and explicit overwrite rules apply; poll the returned jobId for terminal output. Concurrent approval-capable requests fail with approval_pending and create no job.', inputSchema: z.object({ projectId: ProjectIdField, kind: z.enum(['master', 'stems', 'midi', 'dawproject', 'sfx-batch', 'pack']).describe('Export artifact family.'), destination: z.string().min(1).describe('Exact local output path checked by file authority.'), format: z.enum(['wav', 'flac', 'mp3']).optional().describe('Requested audio codec; unsupported codecs fail rather than silently substituting WAV.'), startTick: z.number().int().nonnegative().optional(), endTick: z.number().int().positive().optional(), trackIds: z.array(z.string()).max(500).optional(), overwrite: z.boolean().default(false).describe('Explicit overwrite intent; authority policy still decides.') }).strict(), ...TOOL_OUTPUT, annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: true } }, async ({ projectId, ...request }) => { const id = projectId ?? projects.getActiveProjectId(); if (!id) return jsonText({ error: 'no_open_project' }); return this.startApprovalCapableJob(session, (reservationId) => this.options.exports.start({ projectId: id, ...request } as ExportRequest, session.actor, reservationId)); });

    server.registerTool('job_manage', { title: 'Manage AIMuse jobs', description: 'Owner-only list/inspect/bounded-wait/cancel/dependency. Foreign IDs equal missing IDs. Approval dependencies can only be resolved by a human in AIMuse.', inputSchema: JobSchema, ...TOOL_OUTPUT, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ action, jobId, timeoutMs }) => { if (action === 'list') return jsonText(projects.listJobs(session.actor.id).map(jobSummary)); if (!jobId) return jsonText({ error: 'job_id_required' }); let job = projects.getJob(jobId); if (!job || job.ownerActorId !== session.actor.id) return jsonText({ error: 'job_not_found' }); if (action === 'cancel') { this.options.generation.cancel(jobId); job = projects.cancelJob(jobId) ?? job; this.pending.delete(jobId); } if (action === 'wait' && (timeoutMs ?? 0) > 0) { const deadline = Date.now() + (timeoutMs ?? 0); while (!terminal(job.status) && job.status !== 'waiting-for-user' && Date.now() < deadline) { await new Promise((resolvePromise) => setTimeout(resolvePromise, 100)); job = projects.getJob(jobId) ?? job; } } return jsonText(jobSummary(job)); });
    return server;
  }

  private async fileAction(session: McpSession, path: string, mode: 'read' | 'write', kind: AsyncJob['kind'], summary: string, request: Record<string, unknown>, run: (actor: Actor) => Promise<unknown>) { return this.multiFileAction(session, [{ path, mode }], kind, summary, request, run); }
  private async submitMutation<T>(session: McpSession, projectId: Id, cost: number, run: () => Promise<T>): Promise<AgentMutationResult<T>> { const scheduled = await this.mutationScheduler.submit({ actorId: session.actor.id, projectId, cost, run, onStateChange: () => this.refreshMutationPresence(session) }); this.refreshMutationPresence(session); return scheduled; }
  private refreshMutationPresence(session: McpSession): void { const existing = this.options.projects.getMcpInfo().sessions.find((presence) => presence.actor.id === session.actor.id); if (!existing) return; const state = this.mutationScheduler.status().actors[session.actor.id]; this.options.projects.updatePresence({ ...existing, actor: structuredClone(session.actor), queueDepth: state?.queued ?? 0, status: state?.active ? 'working' : state?.queued ? 'waiting' : 'idle' }); }
  private async multiFileAction(session: McpSession, files: Array<{ path: string; mode: 'read' | 'write' }>, kind: AsyncJob['kind'], summary: string, request: Record<string, unknown>, run: (actor: Actor) => Promise<unknown>) { const actor = structuredClone(session.actor); for (const file of files) { const target = resolve(file.path); const present = await stat(target).then(() => true, () => false); const decision = await this.options.authority.file(target, file.mode, present); if (!decision.allowed) return this.queueApproval(session, kind, decision.approvalKind ?? (file.mode === 'read' ? 'file-read' : 'file-write'), summary, request, run, actor); } return jsonText(await run(actor)); }
  private approvalPending() { return jsonText({ error: 'approval_pending', message: 'Another approval-capable request is being prepared or awaits human review. No job was created.', retryable: true }, { guidance: 'Wait for the single visible approval request to be resolved or cancelled, then retry. AIMuse does not reveal another actor’s approval details.', humanRequired: true }); }
  private async startApprovalCapableJob(session: McpSession, start: (reservationId: Id) => { jobId: Id } | Promise<{ jobId: Id }>) { const reservation = this.options.projects.reserveApproval(session.actor.id); if (!reservation) return this.approvalPending(); try { return jsonText(await start(reservation.reservationId)); } catch (error) { this.options.projects.releaseApprovalReservation(reservation.reservationId); throw error; } }
  private queueApproval(session: McpSession, kind: AsyncJob['kind'], approvalKind: NonNullable<AsyncJob['approval']>['kind'], summary: string, request: Record<string, unknown>, run: (actor: Actor) => Promise<unknown>, authenticatedActor = structuredClone(session.actor)) { const reservation = this.options.projects.reserveApproval(authenticatedActor.id); if (!reservation) return this.approvalPending(); const timestamp = nowIso(); const job: AsyncJob = { id: createId('approval-job'), ownerActorId: authenticatedActor.id, projectId: typeof request.projectId === 'string' ? request.projectId : undefined, kind, status: 'waiting-for-user', progress: 0, message: `${summary} is waiting for in-app approval.`, createdAt: timestamp, updatedAt: timestamp, cancellable: true, approval: { kind: approvalKind, summary, request, expiresAt: new Date(Date.now() + 30 * 60_000).toISOString() }, result: { request } }; if (!this.options.projects.bindApprovalReservation(reservation.reservationId, job.id, authenticatedActor.id)) { this.options.projects.releaseApprovalReservation(reservation.reservationId); return this.approvalPending(); } this.pending.set(job.id, { actor: structuredClone(authenticatedActor), run }); this.options.projects.upsertJob(job); return jsonText({ jobId: job.id, status: job.status, dependency: { type: 'user-approval', approval: job.approval } }, { tool: 'job_manage', arguments: { action: 'wait', jobId: job.id, timeoutMs: 0 }, guidance: 'A human must approve or deny this request in AIMuse. This agent may only poll its owned job.', humanRequired: true }); }
  private async runPending(job: AsyncJob, pending: PendingAction): Promise<void> { this.options.projects.upsertJob({ ...job, status: 'running', progress: 0.1, message: 'Running approved action…', approval: undefined, updatedAt: nowIso() }); try { const output = await pending.run(structuredClone(pending.actor)); this.options.projects.upsertJob({ ...job, status: 'completed', progress: 1, message: 'Approved action completed.', approval: undefined, updatedAt: nowIso(), result: { ...(typeof job.result === 'object' && job.result ? job.result : {}), output } }); } catch (error) { this.options.projects.upsertJob({ ...job, status: 'failed', message: error instanceof Error ? error.message : String(error), approval: undefined, updatedAt: nowIso(), error: { code: 'approved-action-failed', message: error instanceof Error ? error.message : String(error), retryable: false } }); } finally { this.pending.delete(job.id); } }

  private startAudition(projectId: Id, actor: Actor, startTick?: number, endTick?: number, trackIds?: Id[], consolidate = false, trackId?: Id, placeAtTick?: number): { jobId: Id } {
    const jobId = createId(consolidate ? 'consolidate-job' : 'audition-job'); const timestamp = nowIso();
    this.options.projects.upsertJob({ id: jobId, ownerActorId: actor.id, projectId, kind: 'render', status: 'queued', progress: 0, message: consolidate ? 'Consolidation queued.' : 'Audition render queued.', createdAt: timestamp, updatedAt: timestamp, cancellable: true });
    void (async () => {
      try {
        const project = this.options.projects.getProject(projectId); if (!project) throw new Error('Project is not open.');
        const path = join(this.options.cacheRoot, 'auditions', `${jobId}.wav`);
        this.options.projects.upsertJob({ ...this.options.projects.getJob(jobId)!, status: 'running', progress: 0.1, message: 'Rendering auditory observation…', updatedAt: nowIso() });
        const rendered = await this.options.audio.render(project, path, startTick, endTick, trackIds);
        const hashed = await sha256File(path);
        const asset: MediaAsset = { ...entityBase('asset', actor), kind: consolidate ? 'audio' : 'audition', name: `${consolidate ? 'Consolidated' : 'Audition'} ${new Date().toISOString().replace(/[:.]/g, '-')}.wav`, mimeType: 'audio/wav', sha256: hashed.sha256, byteLength: hashed.byteLength, storage: 'managed-cache', externalPath: path, sampleRate: project.settings.sampleRate, channels: 2, durationSamples: rendered.durationSamples, source: 'render' };
        const tx: ProjectTransaction = { id: createId('tx'), clientOperationId: createId('render-asset'), projectId, actor, label: consolidate ? 'Consolidate audio' : 'Create audition render', createdAt: nowIso(), operations: [{ kind: 'asset.add', asset }], checkpointPolicy: 'none' };
        const result = await this.options.projects.apply(tx, actor); if (result.status !== 'committed') throw new Error(result.message ?? 'Render asset could not be registered.');
        this.options.projects.registerAssetSource(asset.id, path);
        if (consolidate && trackId) await this.options.media.createAudioClip(projectId, asset.id, trackId, placeAtTick ?? startTick ?? 0, actor);
        this.options.projects.upsertJob({ ...this.options.projects.getJob(jobId)!, status: 'completed', progress: 1, message: consolidate ? 'Consolidated audio is in the arrangement.' : 'Audition render is ready.', updatedAt: nowIso(), result: { assetId: asset.id, resource: `aimuse://projects/${projectId}/media/${asset.id}`, warnings: rendered.warnings } });
      } catch (error) {
        this.options.projects.upsertJob({ ...this.options.projects.getJob(jobId)!, status: 'failed', message: error instanceof Error ? error.message : String(error), updatedAt: nowIso(), error: { code: 'audition-render-failed', message: error instanceof Error ? error.message : String(error), retryable: true } });
      }
    })();
    return { jobId };
  }
  private async notifyProject(projectId: Id, revision: number): Promise<void> { const uris = [`aimuse://projects/${projectId}/manifest`, `aimuse://projects/${projectId}/snapshot`, `aimuse://projects/${projectId}/changes/${Math.max(0, revision - 1)}`]; for (const session of this.sessions.values()) await Promise.allSettled(uris.filter((uri) => session.resourceSubscriptions.has(uri)).map((uri) => session.mcp.server.sendResourceUpdated({ uri }))); }
  private async readPreferredPort(): Promise<number> { try { const value = JSON.parse(await readFile(this.options.portSettingsPath, 'utf8')) as PortFile; return value.version === 1 ? value.preferredPort : PORT_START; } catch { return PORT_START; } }
}
